# Project information
site_name: 'JTSDK Tools'
site_description: 'Development Frameworks, Librarys and CLI Appllications'
site_author: 'Greg Beam, KI7MT'

# Repository
repo_url: 'https://github.com/ki7mt/jtsdk-tools'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Greg Beam, KI7MT'

nav:
    - Home: 'index.md'
    - Tools:
      - 'Overview': 'tools/cli-tools-overview.md'
      - 'JTEnv': 'tools/jtenv.md'
      - 'JTEnvjv': 'tools/jtenvjv.md'
      - 'JTEnvpy': 'tools/jtenvpy.md'
      - 'JTConfig': 'tools/jtconfig.md'
      - 'JTBuildcm': 'tools/jtbuildcm.md'
      - 'NetCore Global Tools': 'tools/global-tools-overview.md'

# Configuration
theme:
  name: 'flatly'
  language: 'en'

