@ECHO off
:: -----------------------------------------------------------------------------
:: Name ..............: qt-gen-tc.cmd
:: Description .......: Tool Chain Generation Script
:: Author ............: Greg, Beam, KI7MT, <ki7mt@yahoo.com>
:: Copyright .........: Copyright (C) 2014-2018 Greg Beam, KI7MT
:: License ...........: GPL-3
::
:: qt-gen-tc is free software: you can redistribute it and/or modify it
:: under the terms of the GNU General Public License as published by the Free
:: Software Foundation either version 3 of the License, or (at your option) any
:: later version. 
::
:: qt-gen-tc is distributed in the hope that it will be useful, but WITHOUT
:: ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
:: FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
:: details.
::
:: You should have received a copy of the GNU General Public License
:: along with this program.  If not, see <http://www.gnu.org/licenses/>.
::-----------------------------------------------------------------------------::

SETLOCAL
ECHO.
ECHO ------------------------------
ECHO  Generate Tool Chain Files
ECHO ------------------------------
ECHO.
mkdir %JTSDK_HOME%\tools\tc-files >NUL 2>&1

:: Hamlib3 Dirs
SET hamlib_base=%JTSDK_HOME%\tools\hamlib
SET "hamlib_base_f=%hamlib_base:\=/%"
GOTO GEN_QT55

:GEN_QT55
REM ----------------------------------------------------------------------------
REM Tool Chain File for Qt 5.5 using GCC 4.9.2
REM ----------------------------------------------------------------------------
ECHO  Version          : %version%
ECHO  TC File          : QT55.cmake
ECHO  File Path        : %JTSDK_HOME%\tools\tc-files\QT55.cmake

SET QTD55=%JTSDK_HOME%\tools\Qt\5.5\mingw492_32\bin
SET GCCD55=%JTSDK_HOME%\tools\Qt\Tools\mingw492_32\bin
SET "QTD55_F=%QTD55:\=/%"
SET "GCCD55_F=%GCCD55:\=/%"

>%JTSDK_HOME%\tools\tc-files\QT55.cmake (
ECHO # This file is auto-generated by : %~n0.cmd version %version%
ECHO # Tool Chain File for Qt 5.5 using GCC 492_32
ECHO.
ECHO # System Type and Based Paths
ECHO ^SET^(CMAKE_SYSTEM_NAME Windows^)
ECHO ^SET^(QTDIR %QTD55_F%^)
ECHO ^SET^(GCCD %GCCD55_F%^)
ECHO.
ECHO # AsciiDoctor
ECHO ^SET^(ADOCD %ruby_dir_f%^)
ECHO.
ECHO # FFTW
ECHO ^SET^(FFTWD %fftw3f_dir_f%^)
ECHO.
ECHO # Hamlib
ECHO ^SET^(HLBIN %hamlib_base_f%/qt/5.5/bin^)
ECHO ^SET^(HLINC %hamlib_base_f%/qt/5.5/include^)
ECHO ^SET^(HLLIB %hamlib_base_f%/qt/5.5/lib^)
ECHO.
ECHO # Subversion
ECHO ^SET^(SVND %svn_dir_f%^)
ECHO.
ECHO # Cmake Consolidated Variables
ECHO ^SET^(CMAKE_PREFIX_PATH ^${GCCD} ^${QTDIR} ^${ADOCD} ^${FFTWD} ^${SVND} ^${HLBIN} ^${HLINC} ^${HLLIB}^)
ECHO ^SET^(CMAKE_FIND_ROOT_PATH ^${TOOLSROOT}^)
ECHO ^SET^(CMAKE_FIND_ROOT_PATH_PROGRAM NEVER^)
ECHO ^SET^(CMAKE_FIND_ROOT_PATH_LIBRARY BOTH^)
ECHO ^SET^(CMAKE_FIND_ROOT_PATH_INCLUDE BOTH^)
ECHO.
ECHO # END Cmake Tool Chain File
)
GOTO GEN_QT59

:GEN_QT59
REM ----------------------------------------------------------------------------
REM Tool Chain File for Qt 5.9.5 using GCC 5.3.0
REM ----------------------------------------------------------------------------
ECHO.
ECHO  Version          : %version%
ECHO  TC File          : QT59.cmake
ECHO  File Path        : %JTSDK_HOME%\tools\tc-files\QT59.cmake

SET QTD59=%JTSDK_HOME%\tools\Qt\5.9.5\mingw53_32\bin
SET GCCD59=%JTSDK_HOME%\tools\Qt\Tools\mingw530_32\bin
SET "QTD59_F=%QTD59:\=/%"
SET "GCCD59_F=%GCCD59:\=/%"

>%JTSDK_HOME%\tools\tc-files\QT59.cmake (
ECHO # This file is auto-generated by : %~n0.cmd version %version%
ECHO # Tool Chain File for Qt 5.9.5 using GCC 530_32
ECHO.
ECHO # System Type and Based Paths
ECHO ^SET^(CMAKE_SYSTEM_NAME Windows^)
ECHO ^SET^(QTDIR %QTD59_F%^)
ECHO ^SET^(GCCD %GCCD59_F%^)
ECHO.
ECHO # AsciiDoctor
ECHO ^SET^(ADOCD %ruby_dir_f%^)
ECHO.
ECHO # FFTW
ECHO ^SET^(FFTWD %fftw3f_dir_f%^)
ECHO.
ECHO # Hamlib
ECHO ^SET^(HLBIN %hamlib_base_f%/qt/5.9.5/bin^)
ECHO ^SET^(HLINC %hamlib_base_f%/qt/5.9.5/include^)
ECHO ^SET^(HLLIB %hamlib_base_f%/qt/5.9.5/lib^)
ECHO.
ECHO # Subversion
ECHO ^SET^(SVND %svn_dir_f%^)
ECHO.
ECHO # Cmake Consolidated Variables
ECHO ^SET^(CMAKE_PREFIX_PATH ^${GCCD} ^${QTDIR} ^${ADOCD} ^${FFTWD} ^${SVND} ^${HLBIN} ^${HLINC} ^${HLLIB}^)
ECHO ^SET^(CMAKE_FIND_ROOT_PATH ^${TOOLSROOT}^)
ECHO ^SET^(CMAKE_FIND_ROOT_PATH_PROGRAM NEVER^)
ECHO ^SET^(CMAKE_FIND_ROOT_PATH_LIBRARY BOTH^)
ECHO ^SET^(CMAKE_FIND_ROOT_PATH_INCLUDE BOTH^)
ECHO.
ECHO # END Cmake Tool Chain File
)
GOTO EOF

:EOF
ECHO.
ENDLOCAL

exit /b 0