#!/usr/bin/env bash

set -e

# check the Apache Gradle Website and adjust version as needed
# https://services.gradle.org/distributions/
version="5.2"
url="https://services.gradle.org/distributions/gradle-$version-bin.zip"

# set script variables
config_dir="$HOME/.config/jtsdk-tools"
gradle_env="$config_dir/env/gradle-env.sh"

# ensure env directory exists
mkdir -p "$config_dir/env" &>/dev/null

# Install Prequisits
clear ||:
echo "================================="
echo "Installing Gradle"
echo "================================="

# check in repository has already been added
if [[ ! -d /opt/gradle-$version ]]; then
    
    echo "* Downloading Gradle Version : $version"
    sudo wget -c -N --progress=dot "$url" -P /tmp
    
    echo "* Extracting gradle-$version.zip"
    sudo unzip -q -d /opt /tmp/gradle-"$version"-bin.zip

    # to prevent any link errors, unlink /opt/gradle first
    echo "* Linking /opt/gradle-$version to /opt/gradle"

    # unlink if xists
    if [[ -L /opt/gradle ]]; then
        sudo unlink /opt/gradle
    fi

    # Link the new version
    sudo ln -s /opt/gradle-"$version" /opt/gradle

    # generate gradle-env.sh script
    echo "* Generate Gradle Envirnment Script"
    rm -f "$gradle_env" &>/dev/null
    touch "$gradle_env" &>/dev/null

# create the here doc
(
cat <<'EOF_GRADLE_ENV'
#!/usr/bin/env bash

# Auto Generated by gradle-setup.sh

# Project ......: JTSDK-Tools
# File .........: gradle-env.sh
# Author .......: Greg Beam (KI7MT)
# Description ..: Environment variables for Gradle Build Tools
# Usage.........: Source this script to use Gradle environment variabes
#
# Example:
#       source /home/$USER/.config/jtsdk-tools/env/gradle-env.sh
#       gradle --version

# set variables
export GRADLE_HOME=/opt/gradle
export PATH=${GRADLE_HOME}/bin:${PATH}

# End Gradle Environment Script
EOF_GRADLE_ENV
) > "$gradle_env"

    # source the env script
    echo "* Sourcing : $gradle_env"
    source "$gradle_env"
    echo "* Run Version Check"
    gradle --version
    echo ""
    echo "Finished Installing Gradle Version $version"
    echo ""

else
    echo "* Gradle Version : $version is already installed"
    echo ""
fi

# End Gradle Installation